from fpdf import FPDF
from fpdf.enums import XPos, YPos

from src.db.supabase_client import get_report, get_markers_for_report

_NEXT_LINE = {"new_x": XPos.LMARGIN, "new_y": YPos.NEXT}

# Core Helvetica is latin-1 only; agent summaries carry em-dashes and curly
# quotes, which otherwise raise FPDFUnicodeEncodingException.
_CHAR_MAP = str.maketrans({
    "—": "-", "–": "-",      # em/en dash
    "‘": "'", "’": "'",      # curly single quotes
    "“": '"', "”": '"',      # curly double quotes
    "…": "...", " ": " ", "•": "-",
})


def _latin1_safe(text: str) -> str:
    return str(text).translate(_CHAR_MAP).encode("latin-1", "replace").decode("latin-1")


def _fmt(value) -> str:
    """None-safe string — explicit check so 0.0 renders as '0.0', not blank."""
    return "-" if value is None else _latin1_safe(value)


def _ref_range(ref_low, ref_high) -> str:
    if ref_low is not None and ref_high is not None:
        return f"{ref_low} - {ref_high}"
    if ref_high is not None:
        return f"< {ref_high}"
    if ref_low is not None:
        return f"> {ref_low}"
    return "-"


def generate_report_pdf(report_id: str, summary: str | None = None) -> bytes:
    report = get_report(report_id)
    if report is None:
        raise ValueError(f"Report not found: {report_id}")
    markers = get_markers_for_report(report_id)

    pdf = FPDF()
    pdf.set_margins(15, 15, 15)
    pdf.add_page()

    # ── Title ────────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, "Blood Report Analysis", align="C", **_NEXT_LINE)
    pdf.ln(4)

    # ── Patient / report header ───────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, "Patient Information", **_NEXT_LINE)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_fill_color(245, 245, 245)

    fields = [
        ("Lab",            _fmt(report.get("lab_name"))),
        ("Report Date",    _fmt(report.get("report_date"))),
        ("Patient Age",    _fmt(report.get("patient_age"))),
        ("Patient Gender", _fmt(report.get("patient_gender"))),
    ]
    for label, val in fields:
        pdf.cell(45, 7, label + ":", border=0)
        pdf.cell(0, 7, val, **_NEXT_LINE)
    pdf.ln(4)

    # ── Interpretation (optional) ─────────────────────────────────────────────
    if summary:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 7, "Interpretation", **_NEXT_LINE)
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 6, _latin1_safe(summary))
        pdf.ln(4)

    # ── Markers table ─────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, "Test Results", **_NEXT_LINE)

    col_w = {"name": 68, "value": 22, "unit": 22, "ref": 42, "flag": 22}

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(220, 220, 220)
    pdf.cell(col_w["name"], 7, "Name",      border=1, fill=True)
    pdf.cell(col_w["value"], 7, "Value",    border=1, fill=True, align="R")
    pdf.cell(col_w["unit"],  7, "Unit",     border=1, fill=True)
    pdf.cell(col_w["ref"],   7, "Ref Range",border=1, fill=True)
    pdf.cell(col_w["flag"],  7, "Flag",     border=1, fill=True, **_NEXT_LINE)

    pdf.set_font("Helvetica", "", 9)
    for m in markers:
        flag = (m.get("flag") or "").upper()
        if flag == "HIGH":
            pdf.set_text_color(180, 0, 0)
        elif flag == "LOW":
            pdf.set_text_color(180, 90, 0)
        else:
            pdf.set_text_color(0, 0, 0)

        # Numeric value, else text result (e.g. GFR category "G1"), else "-"
        if m.get("value") is not None:
            value = str(m["value"])
        elif m.get("value_text") is not None:
            value = _latin1_safe(m["value_text"])
        else:
            value = "-"

        pdf.cell(col_w["name"],  7, _latin1_safe(m.get("name") or ""), border=1)
        pdf.cell(col_w["value"], 7, value,                           border=1, align="R")
        pdf.cell(col_w["unit"],  7, _latin1_safe(m.get("unit") or ""), border=1)
        pdf.cell(col_w["ref"],   7, _ref_range(m.get("ref_low"), m.get("ref_high")), border=1)
        pdf.cell(col_w["flag"],  7, flag or "-",                     border=1, **_NEXT_LINE)

    pdf.set_text_color(0, 0, 0)
    pdf.ln(6)

    # ── Disclaimer footer ─────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(
        0, 5,
        "This report is generated by an automated tool and is not medical advice. "
        "Consult a qualified physician for interpretation.",
    )

    return bytes(pdf.output())
